web_server/__init__.py
from flask import Flask, render_template, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_mysqldb import MySQL
from os import path
from flask_login import LoginManager


server = Flask(__name__)
server.config['SECRET_KEY'] ="secretkey"
# SQL alchemy database 
# server.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:@localhost/user'
server.config['MYSQL_HOST'] = 'localhost'
server.config['MYSQL_USER'] = 'root'
server.config['MYSQL_PASSWORD'] = ''
server.config['MYSQL_DB'] = 'user'
server.config['MYSQL_CURSORCLASS'] = 'DictCursor'


# db = SQLAlchemy(app)
# class for model 
# class UserInfo(db.Model):
 #    id = db.Column(db.Integer, primary_key=True)
 #    username = db.Column(db.String(80), unique=True, nullable=False)
 #    email = db.Column(db.String(120), unique=True, nullable=False)


mysql = MySQL(server)

from .views import views
from .auth import auth

server.register_blueprint(views, url_prefix="/")
server.register_blueprint(auth, url_prefix="/")

web_server/auth.py
from flask import Blueprint, render_template, redirect, request, url_for
from web_server import mysql
import MySQLdb.cursors
auth = Blueprint("auth", __name__)



@auth.route("/sign-in", methods=['POST','GET'])
def login():
	return render_template("signin.html")
   
@auth.route("/sign-up", methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        print(username)
        print(password)
        cursor = mysql.connection.cursor()
        cursor.execute('INSERT INTO user_info (username, password) VALUES (%s, %s)', (username, password ))
        mysql.connection.commit()
        cursor.close()  
#       INSERT INTO table_name (column1, column2, column3, ...)
#       VALUES (value1, value2, value3, ...);
    return render_template("signup.html")

@auth.route("/sign-out")
def logout():
    return redirect(url_for("views.home"))
   

web_server/views.py
from flask import Blueprint, render_template

views = Blueprint("views", __name__)

@views.route("/home")
def home():
	return render_template("index.html")

web_server/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename ='style.css')}}">

    <title>
    {% block title %}

    {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('views.home')}}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('views.home')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.register')}}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('auth.login')}}">Sign In</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>
    
    <div class="container">
    {% block body %}




    {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

web_server/templates/index.html
{% extends "base.html" %}
{% block title %}
  Home
{% endblock %}
{% block body %}
<div class="container">
  <h2 align="center">Home Page</h2>
</div>
{% endblock %}

web_server/templates/signin.html
{% extends "base.html" %}
{% block title %}
	login_page
{% endblock %}
{% block body %}
<h1 align="center">Login Page</h1>
<div class="container" >
	<form method="POST">
	  <div class="col-md-6">
	    <label for="email" >Email address</label>
	    <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email">
	    
	  </div>
	  <div class="col-md-6">
	    <label for="password" class="form-label">Password</label>
	    <input type="password" class="form-control" name="password" id="password" placeholder="password">
	  </div>
	  <div class="mt-3 form-check">
	  <button type="submit" class="btn btn-primary">
	  	Sign In
	  </button>
	  </div>
	</form>
</div>
{% endblock %}

web_server/templates/signup.html
{% extends "base.html" %}
{% block title %}
	signup_page
{% endblock %}
{% block body %}
<h1 align="center" >SignUP page</h1>
<div class="container" >
	<form method="POST">
	  <div class="col-md-6">
	    <label for="email" >Email address</label>
	    <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email">
	    
	  </div>

	  <div class="col-md-6">
	    <label for="username" >Username</label>
	    <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username">
	    
	  </div>

	  <div class="col-md-6">
	    <label for="password" class="form-label">Password</label>
	    <input type="password" class="form-control" name="password" id="password" placeholder="password">

	    <label for="re-password" class="form-label">Re-Password</label>
	    <input type="password" class="form-control" name="re-password" id="re-password" placeholder="Re-Enter Password">

	  </div>
	  <div class="mt-3 form-check">
	  <button type="submit" class="btn btn-primary">
	  	Sign In
	  </button>
	  </div>
	</form>
</div>
{% endblock %}